[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []
unmaintained = "workspace"
yanked = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["CDDL-1.0"], crate = "inferno" },
]
unused-allowed-license = "warn"

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
