name: "mobench"
description: "Run mobile benchmarks with mobench"
inputs:
  command:
    description: "Command to invoke (default: cargo mobench run)"
    required: false
    default: "cargo mobench run"
  run-args:
    description: "Arguments passed to mobench run"
    required: true
  ci:
    description: "Append --ci to the command"
    required: false
    default: "true"
  install-mobench:
    description: "Install mobench with cargo-binstall or cargo install"
    required: false
    default: "true"
  mobench-version:
    description: "Optional mobench version to install"
    required: false
    default: ""
  install-cargo-ndk:
    description: "Install cargo-ndk"
    required: false
    default: "true"
  setup-android:
    description: "Setup Android SDK/NDK"
    required: false
    default: "true"
  ndk-version:
    description: "Android NDK version"
    required: false
    default: "26.1.10909125"
  android-sdk-root:
    description: "Android SDK root directory on the runner"
    required: false
    default: "/usr/local/lib/android/sdk"
  android-packages:
    description: "SDK packages to install via setup-android"
    required: false
    default: |
      platform-tools
      platforms;android-34
      build-tools;34.0.0
      ndk;26.1.10909125
  cache-cargo:
    description: "Cache cargo registry/git and target"
    required: false
    default: "true"
  cache-target:
    description: "Cache Cargo target/ directory (can be large)"
    required: false
    default: "true"
  cache-gradle:
    description: "Cache Gradle wrapper and caches (useful if mobench triggers Gradle builds)"
    required: false
    default: "true"
  cache-android:
    description: "Cache Android SDK/NDK"
    required: false
    default: "true"
  artifact-name:
    description: "Artifact name for upload"
    required: false
    default: "mobench-results"
  artifact-path:
    description: "Paths to upload as artifacts"
    required: false
    default: |
      target/mobench/results.json
      target/mobench/results.md
      target/mobench/results.csv
      target/browserstack
runs:
  using: "composite"
  steps:
    - name: Cache cargo
      if: inputs.cache-cargo == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache target
      if: inputs.cache-target == 'true'
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-

    - name: Cache Gradle
      if: inputs.cache-gradle == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Android SDK
      if: inputs.cache-android == 'true' && inputs.setup-android == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.android-sdk-root }}/ndk/${{ inputs.ndk-version }}
          ${{ inputs.android-sdk-root }}/platform-tools
          ${{ inputs.android-sdk-root }}/platforms
          ${{ inputs.android-sdk-root }}/build-tools
        key: ${{ runner.os }}-android-${{ inputs.ndk-version }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Setup Android SDK/NDK
      if: inputs.setup-android == 'true'
      uses: android-actions/setup-android@v3
      with:
        packages: ${{ inputs.android-packages }}

    - name: Install cargo-ndk
      if: inputs.install-cargo-ndk == 'true'
      shell: bash
      run: |
        if ! command -v cargo-ndk >/dev/null 2>&1; then
          cargo install cargo-ndk
        fi

    - name: Install mobench
      if: inputs.install-mobench == 'true'
      shell: bash
      run: |
        if command -v cargo-mobench >/dev/null 2>&1 || command -v mobench >/dev/null 2>&1; then
          exit 0
        fi
        version_flag=""
        if [ -n "${{ inputs.mobench-version }}" ]; then
          version_flag="--version ${{ inputs.mobench-version }}"
        fi
        if command -v cargo-binstall >/dev/null 2>&1; then
          cargo binstall -y mobench $version_flag
        else
          cargo install cargo-binstall
          cargo binstall -y mobench $version_flag
        fi

    - name: Run mobench
      shell: bash
      run: |
        export ANDROID_SDK_ROOT="${{ inputs.android-sdk-root }}"
        export ANDROID_HOME="${{ inputs.android-sdk-root }}"
        export ANDROID_NDK_HOME="${{ inputs.android-sdk-root }}/ndk/${{ inputs.ndk-version }}"
        extra_args=""
        if [ "${{ inputs.ci }}" = "true" ]; then
          extra_args="--ci"
        fi
        ${{ inputs.command }} $extra_args ${{ inputs.run-args }}

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
