name: BenchRunner
options:
  bundleIdPrefix: dev.world
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  BenchRunner:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: BenchRunner
    info:
      path: BenchRunner/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.world.bench
        SWIFT_OBJC_BRIDGING_HEADER: BenchRunner/BenchRunner-Bridging-Header.h
    dependencies:
      - framework: ../../target/ios/sample_fns.xcframework
        embed: true
        link: true
