[package]
name = "basic-benchmark"
version = "0.1.0"
edition = "2021"
license.workspace = true
rust-version.workspace = true

[lib]
name = "basic_benchmark"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
mobench-sdk = { path = "../../crates/mobench-sdk" }
inventory.workspace = true
serde.workspace = true
thiserror.workspace = true
uniffi = { workspace = true, features = ["cli"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
